#!/usr/bin/env python3
"""
Seed script: create 30 realistic Malaysian suppliers.

Distribution: Chinese 20 + Malay 8 + Indian 2
All TINs follow format C + 10 digits (corporate).
MSIC codes are from the set seeded by seed_reference_data.py.
Postcode/state combinations are geographically correct.

Run inside the container:
  docker compose exec backend python scripts/seed_suppliers.py

Idempotent: safe to re-run; existing records (by code) are skipped.
"""

from __future__ import annotations

import asyncio
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

import structlog
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession, async_sessionmaker, create_async_engine

from app.core.config import settings
from app.models.partner import Supplier

log = structlog.get_logger()

# ---------------------------------------------------------------------------
# Supplier data
# Each tuple:
#   (code, name, tin, registration_no, msic_code,
#    address_line1, city, state, postcode, country,
#    phone, email, contact_person,
#    currency_code, payment_terms_days, credit_limit_str)
# ---------------------------------------------------------------------------

SUPPLIERS: list[dict] = [
    # ── Chinese suppliers (1-20) ────────────────────────────────────────────
    {
        "code": "SUP-001",
        "name": "Tan Chong Trading Sdn Bhd",
        "tin": "C1234567890",
        "registration_no": "20010312345",
        "msic_code": "46310",
        "address_line1": "No. 12, Jalan SS 2/55",
        "city": "Petaling Jaya",
        "state": "Selangor",
        "postcode": "47300",
        "country": "MY",
        "phone": "+60 3-7876 1234",
        "email": "sales@tanchong-trading.com.my",
        "contact_person": "Kevin Tan Chong Wei",
        "currency_code": "MYR",
        "payment_terms_days": 30,
        "credit_limit": "50000.00",
    },
    {
        "code": "SUP-002",
        "name": "Lim Brothers Food Supply Sdn Bhd",
        "tin": "C2345678901",
        "registration_no": "20050515678",
        "msic_code": "46310",
        "address_line1": "Lot 8, Jalan Industri Batu Caves 1/2",
        "city": "Batu Caves",
        "state": "Selangor",
        "postcode": "68100",
        "country": "MY",
        "phone": "+60 3-6189 5678",
        "email": "info@limbros.com.my",
        "contact_person": "David Lim Kok Weng",
        "currency_code": "MYR",
        "payment_terms_days": 30,
        "credit_limit": "80000.00",
    },
    {
        "code": "SUP-003",
        "name": "Wong & Sons Distribution Sdn Bhd",
        "tin": "C3456789012",
        "registration_no": "19980620987",
        "msic_code": "46900",
        "address_line1": "No. 5A, Jalan Klang Lama",
        "city": "Kuala Lumpur",
        "state": "Kuala Lumpur",
        "postcode": "58000",
        "country": "MY",
        "phone": "+60 3-7982 3456",
        "email": "wongs.dist@gmail.com",
        "contact_person": "Jason Wong Boon Seng",
        "currency_code": "MYR",
        "payment_terms_days": 45,
        "credit_limit": "60000.00",
    },
    {
        "code": "SUP-004",
        "name": "Ong Kee Fatt Enterprise",
        "tin": "C4567890123",
        "registration_no": "20030808543",
        "msic_code": "46310",
        "address_line1": "No. 22, Lorong Ong Kim Wee 3",
        "city": "Melaka",
        "state": "Melaka",
        "postcode": "75000",
        "country": "MY",
        "phone": "+60 6-283 4567",
        "email": "ongkf.enterprise@yahoo.com",
        "contact_person": "Michael Ong Kee Fatt",
        "currency_code": "MYR",
        "payment_terms_days": 30,
        "credit_limit": "30000.00",
    },
    {
        "code": "SUP-005",
        "name": "Cheah Healthcare Supplies Sdn Bhd",
        "tin": "C5678901234",
        "registration_no": "20110225112",
        "msic_code": "46900",
        "address_line1": "Unit 3-1, Menara Maxisegar, Jalan Pandan Indah 4/2",
        "city": "Kuala Lumpur",
        "state": "Kuala Lumpur",
        "postcode": "55100",
        "country": "MY",
        "phone": "+60 3-4291 5000",
        "email": "procurement@cheah-health.com.my",
        "contact_person": "Grace Cheah Siew Lin",
        "currency_code": "MYR",
        "payment_terms_days": 60,
        "credit_limit": "100000.00",
    },
    {
        "code": "SUP-006",
        "name": "Ng Kim Huat Wholesale Trading",
        "tin": "C6789012345",
        "registration_no": "20060614321",
        "msic_code": "46310",
        "address_line1": "No. 45, Jalan Pasar, Kuchai Lama",
        "city": "Kuala Lumpur",
        "state": "Kuala Lumpur",
        "postcode": "58200",
        "country": "MY",
        "phone": "+60 3-7984 6789",
        "email": "ngkimhuat.trading@hotmail.com",
        "contact_person": "Bryan Ng Kim Huat",
        "currency_code": "MYR",
        "payment_terms_days": 30,
        "credit_limit": "40000.00",
    },
    {
        "code": "SUP-007",
        "name": "Chan Mun Keong & Sons Sdn Bhd",
        "tin": "C7890123456",
        "registration_no": "20000405765",
        "msic_code": "46410",
        "address_line1": "No. 88, Jalan Masjid India",
        "city": "Kuala Lumpur",
        "state": "Kuala Lumpur",
        "postcode": "50100",
        "country": "MY",
        "phone": "+60 3-2698 7890",
        "email": "cmk.sons@gmail.com",
        "contact_person": "Vincent Chan Mun Keong",
        "currency_code": "MYR",
        "payment_terms_days": 30,
        "credit_limit": "45000.00",
    },
    {
        "code": "SUP-008",
        "name": "Yeoh Brothers Distributors Sdn Bhd",
        "tin": "C8901234567",
        "registration_no": "20080710234",
        "msic_code": "46310",
        "address_line1": "Bangunan Yeoh, No. 1, Jalan Tun Hussein Onn",
        "city": "Georgetown",
        "state": "Pulau Pinang",
        "postcode": "10050",
        "country": "MY",
        "phone": "+60 4-261 8901",
        "email": "yeohbros@streamyx.com",
        "contact_person": "Raymond Yeoh Boon Khim",
        "currency_code": "MYR",
        "payment_terms_days": 45,
        "credit_limit": "70000.00",
    },
    {
        "code": "SUP-009",
        "name": "Koh Heng Bee Trading Company",
        "tin": "C9012345678",
        "registration_no": "19950320111",
        "msic_code": "46900",
        "address_line1": "No. 33, Lebuh Pantai",
        "city": "Georgetown",
        "state": "Pulau Pinang",
        "postcode": "10300",
        "country": "MY",
        "phone": "+60 4-262 9012",
        "email": "kohengbee@gmail.com",
        "contact_person": "Steven Koh Heng Bee",
        "currency_code": "MYR",
        "payment_terms_days": 30,
        "credit_limit": "35000.00",
    },
    {
        "code": "SUP-010",
        "name": "Teh Food Industries Sdn Bhd",
        "tin": "C0123456789",
        "registration_no": "20120515987",
        "msic_code": "10710",
        "address_line1": "PLO 128, Jalan Kempas Baru",
        "city": "Johor Bahru",
        "state": "Johor",
        "postcode": "81300",
        "country": "MY",
        "phone": "+60 7-237 0123",
        "email": "teh.industries@gmail.com",
        "contact_person": "Danny Teh Cheng Hock",
        "currency_code": "MYR",
        "payment_terms_days": 30,
        "credit_limit": "55000.00",
    },
    {
        "code": "SUP-011",
        "name": "Low Hin Fatt Consumer Goods Sdn Bhd",
        "tin": "C1122334455",
        "registration_no": "20040901543",
        "msic_code": "46310",
        "address_line1": "No. 7, Jalan Utama 2",
        "city": "Ipoh",
        "state": "Perak",
        "postcode": "30250",
        "country": "MY",
        "phone": "+60 5-549 1122",
        "email": "lowhin.cg@yahoo.com.my",
        "contact_person": "Patrick Low Hin Fatt",
        "currency_code": "MYR",
        "payment_terms_days": 30,
        "credit_limit": "40000.00",
    },
    {
        "code": "SUP-012",
        "name": "Chong Household Products Trading",
        "tin": "C2233445566",
        "registration_no": "20090615432",
        "msic_code": "46900",
        "address_line1": "No. 15, Jalan Permas Jaya 4",
        "city": "Johor Bahru",
        "state": "Johor",
        "postcode": "81750",
        "country": "MY",
        "phone": "+60 7-386 2233",
        "email": "chong.household@gmail.com",
        "contact_person": "Kelvin Chong Wai Kit",
        "currency_code": "MYR",
        "payment_terms_days": 45,
        "credit_limit": "30000.00",
    },
    {
        "code": "SUP-013",
        "name": "Foo Yuen Electrical Supplies Sdn Bhd",
        "tin": "C3344556677",
        "registration_no": "20070220765",
        "msic_code": "46690",
        "address_line1": "Wisma Foo Yuen, Jalan Gombak",
        "city": "Kuala Lumpur",
        "state": "Kuala Lumpur",
        "postcode": "53000",
        "country": "MY",
        "phone": "+60 3-4022 3344",
        "email": "fooyuen.elec@gmail.com",
        "contact_person": "Albert Foo Yuen Meng",
        "currency_code": "MYR",
        "payment_terms_days": 60,
        "credit_limit": "120000.00",
    },
    {
        "code": "SUP-014",
        "name": "Goh Wellness Pharmacy Supplies",
        "tin": "C4455667788",
        "registration_no": "20150310234",
        "msic_code": "46900",
        "address_line1": "No. 21, Jalan Maharajalela",
        "city": "Kuala Lumpur",
        "state": "Kuala Lumpur",
        "postcode": "50150",
        "country": "MY",
        "phone": "+60 3-2274 4455",
        "email": "goh.wellness@gmail.com",
        "contact_person": "Cindy Goh Pei Shan",
        "currency_code": "MYR",
        "payment_terms_days": 30,
        "credit_limit": "50000.00",
    },
    {
        "code": "SUP-015",
        "name": "Quek Pacific Trading Sdn Bhd",
        "tin": "C5566778899",
        "registration_no": "20010718543",
        "msic_code": "46310",
        "address_line1": "No. 3, Jalan Puchong Batu 10",
        "city": "Puchong",
        "state": "Selangor",
        "postcode": "47100",
        "country": "MY",
        "phone": "+60 3-8061 5566",
        "email": "quek.pacific@yahoo.com",
        "contact_person": "Eric Quek Chung Soon",
        "currency_code": "MYR",
        "payment_terms_days": 30,
        "credit_limit": "60000.00",
    },
    {
        "code": "SUP-016",
        "name": "Liew & Co Stationery Sdn Bhd",
        "tin": "C6677889900",
        "registration_no": "20030415876",
        "msic_code": "46900",
        "address_line1": "No. 50, Jalan Pahang",
        "city": "Kuala Lumpur",
        "state": "Kuala Lumpur",
        "postcode": "53000",
        "country": "MY",
        "phone": "+60 3-4042 6677",
        "email": "liew.stationery@gmail.com",
        "contact_person": "Penny Liew Mei Ling",
        "currency_code": "MYR",
        "payment_terms_days": 30,
        "credit_limit": "25000.00",
    },
    {
        "code": "SUP-017",
        "name": "Chua Boon Leong Beverages Sdn Bhd",
        "tin": "C7788990011",
        "registration_no": "20020614321",
        "msic_code": "46310",
        "address_line1": "No. 1, Jalan Subang Permai 6",
        "city": "Shah Alam",
        "state": "Selangor",
        "postcode": "40150",
        "country": "MY",
        "phone": "+60 3-5632 7788",
        "email": "chuabl.bev@gmail.com",
        "contact_person": "Marcus Chua Boon Leong",
        "currency_code": "MYR",
        "payment_terms_days": 45,
        "credit_limit": "75000.00",
    },
    {
        "code": "SUP-018",
        "name": "Heng Ah Kow Wholesale Sdn Bhd",
        "tin": "C8899001122",
        "registration_no": "19980920432",
        "msic_code": "46310",
        "address_line1": "No. 99, Jalan Chow Kit",
        "city": "Kuala Lumpur",
        "state": "Kuala Lumpur",
        "postcode": "50480",
        "country": "MY",
        "phone": "+60 3-4043 8899",
        "email": "hengak.wholesale@hotmail.com",
        "contact_person": "Thomas Heng Ah Kow",
        "currency_code": "MYR",
        "payment_terms_days": 30,
        "credit_limit": "55000.00",
    },
    {
        "code": "SUP-019",
        "name": "Sim Advance Electronics Sdn Bhd",
        "tin": "C9900112233",
        "registration_no": "20100215765",
        "msic_code": "46690",
        "address_line1": "Unit L3-12, Plaza Low Yat",
        "city": "Kuala Lumpur",
        "state": "Kuala Lumpur",
        "postcode": "55100",
        "country": "MY",
        "phone": "+60 3-2145 9900",
        "email": "sim.advance@gmail.com",
        "contact_person": "Andrew Sim Kok Meng",
        "currency_code": "MYR",
        "payment_terms_days": 60,
        "credit_limit": "90000.00",
    },
    {
        "code": "SUP-020",
        "name": "Pang Lai Kee Food Trading",
        "tin": "C0011223344",
        "registration_no": "20050830234",
        "msic_code": "46310",
        "address_line1": "No. 6, Jalan Wangsa Setia 1",
        "city": "Kuala Lumpur",
        "state": "Kuala Lumpur",
        "postcode": "53300",
        "country": "MY",
        "phone": "+60 3-4142 0011",
        "email": "panglk.food@gmail.com",
        "contact_person": "Norman Pang Lai Kee",
        "currency_code": "MYR",
        "payment_terms_days": 30,
        "credit_limit": "35000.00",
    },
    # ── Malay suppliers (21-28) ─────────────────────────────────────────────
    {
        "code": "SUP-021",
        "name": "Syarikat Ahmad Maju Sdn Bhd",
        "tin": "C1223344556",
        "registration_no": "20040712432",
        "msic_code": "46900",
        "address_line1": "No. 11, Jalan Ipoh",
        "city": "Kuala Lumpur",
        "state": "Kuala Lumpur",
        "postcode": "51200",
        "country": "MY",
        "phone": "+60 3-4043 1223",
        "email": "syarikat.ahmadmaju@gmail.com",
        "contact_person": "Dato Ahmad bin Ismail",
        "currency_code": "MYR",
        "payment_terms_days": 30,
        "credit_limit": "40000.00",
    },
    {
        "code": "SUP-022",
        "name": "Perniagaan Razif & Anak-Anak",
        "tin": "C2334455667",
        "registration_no": "20060520543",
        "msic_code": "46310",
        "address_line1": "Lot 5, Jalan Bukit Kerinchi",
        "city": "Kuala Lumpur",
        "state": "Kuala Lumpur",
        "postcode": "59200",
        "country": "MY",
        "phone": "+60 3-2282 2334",
        "email": "razif.perniagaan@yahoo.com",
        "contact_person": "Mohd Razif bin Rahman",
        "currency_code": "MYR",
        "payment_terms_days": 30,
        "credit_limit": "30000.00",
    },
    {
        "code": "SUP-023",
        "name": "Mustafa Halal Food Distributors Sdn Bhd",
        "tin": "C3445566778",
        "registration_no": "20080415876",
        "msic_code": "46310",
        "address_line1": "No. 20, Persiaran PKNS",
        "city": "Shah Alam",
        "state": "Selangor",
        "postcode": "40150",
        "country": "MY",
        "phone": "+60 3-5531 3445",
        "email": "mustafa.halal@gmail.com",
        "contact_person": "Ustaz Mustafa bin Hashim",
        "currency_code": "MYR",
        "payment_terms_days": 45,
        "credit_limit": "65000.00",
    },
    {
        "code": "SUP-024",
        "name": "Azman Global Supplies Sdn Bhd",
        "tin": "C4556677889",
        "registration_no": "20110720987",
        "msic_code": "46900",
        "address_line1": "Jalan Perak 2, Taman Perindustrian Senai",
        "city": "Senai",
        "state": "Johor",
        "postcode": "81400",
        "country": "MY",
        "phone": "+60 7-599 4556",
        "email": "azman.global@gmail.com",
        "contact_person": "Azman bin Yusof",
        "currency_code": "MYR",
        "payment_terms_days": 30,
        "credit_limit": "50000.00",
    },
    {
        "code": "SUP-025",
        "name": "Halim Trading & Services",
        "tin": "C5667788990",
        "registration_no": "20140310234",
        "msic_code": "46310",
        "address_line1": "No. 7, Jalan Wan Alwi",
        "city": "Kuching",
        "state": "Sarawak",
        "postcode": "93350",
        "country": "MY",
        "phone": "+60 82-246 5667",
        "email": "halim.trading@yahoo.com",
        "contact_person": "Abdul Halim bin Ibrahim",
        "currency_code": "MYR",
        "payment_terms_days": 60,
        "credit_limit": "25000.00",
    },
    {
        "code": "SUP-026",
        "name": "Syarikat Faridah Mega Sdn Bhd",
        "tin": "C6778899001",
        "registration_no": "20090901543",
        "msic_code": "46900",
        "address_line1": "No. 3, Jalan Aman 1, Taman Aman",
        "city": "Alor Setar",
        "state": "Kedah",
        "postcode": "05400",
        "country": "MY",
        "phone": "+60 4-773 6778",
        "email": "faridah.mega@gmail.com",
        "contact_person": "Puan Faridah binti Othman",
        "currency_code": "MYR",
        "payment_terms_days": 30,
        "credit_limit": "20000.00",
    },
    {
        "code": "SUP-027",
        "name": "Perusahaan Zulkifli Enterprise",
        "tin": "C7889900112",
        "registration_no": "20020615432",
        "msic_code": "46310",
        "address_line1": "No. 14, Jalan Besar, Butterworth",
        "city": "Butterworth",
        "state": "Pulau Pinang",
        "postcode": "12000",
        "country": "MY",
        "phone": "+60 4-323 7889",
        "email": "zulkifli.enterprise@hotmail.com",
        "contact_person": "Zulkifli bin Mohamad",
        "currency_code": "MYR",
        "payment_terms_days": 30,
        "credit_limit": "30000.00",
    },
    {
        "code": "SUP-028",
        "name": "Norzaida Herbal & Health Products",
        "tin": "C8990011223",
        "registration_no": "20160420765",
        "msic_code": "46900",
        "address_line1": "No. 5, Jalan Tok Hakim",
        "city": "Kota Bharu",
        "state": "Kelantan",
        "postcode": "15050",
        "country": "MY",
        "phone": "+60 9-744 8990",
        "email": "norzaida.herbal@gmail.com",
        "contact_person": "Norzaida binti Zainudin",
        "currency_code": "MYR",
        "payment_terms_days": 45,
        "credit_limit": "20000.00",
    },
    # ── Indian suppliers (29-30) ────────────────────────────────────────────
    {
        "code": "SUP-029",
        "name": "Raju Brothers Distributors Sdn Bhd",
        "tin": "C9001122334",
        "registration_no": "20001115876",
        "msic_code": "46310",
        "address_line1": "No. 22, Jalan Masjid India",
        "city": "Kuala Lumpur",
        "state": "Kuala Lumpur",
        "postcode": "50100",
        "country": "MY",
        "phone": "+60 3-2698 9001",
        "email": "raju.brothers@gmail.com",
        "contact_person": "Rajendran a/l Subramaniam",
        "currency_code": "MYR",
        "payment_terms_days": 30,
        "credit_limit": "45000.00",
    },
    {
        "code": "SUP-030",
        "name": "Priya Ramachandran Trading Co",
        "tin": "C0112233445",
        "registration_no": "20120815234",
        "msic_code": "46900",
        "address_line1": "No. 8, Jalan Leboh Ampang",
        "city": "Kuala Lumpur",
        "state": "Kuala Lumpur",
        "postcode": "50100",
        "country": "MY",
        "phone": "+60 3-2070 0112",
        "email": "priya.trading@gmail.com",
        "contact_person": "Priya a/p Ramachandran",
        "currency_code": "MYR",
        "payment_terms_days": 30,
        "credit_limit": "35000.00",
    },
]


async def seed_suppliers(session: AsyncSession) -> int:
    existing_result = await session.execute(select(Supplier.code))
    existing_codes = {row[0] for row in existing_result.all()}

    created = 0
    for sup in SUPPLIERS:
        if sup["code"] in existing_codes:
            log.info("supplier_exists", code=sup["code"])
            continue

        from decimal import Decimal

        supplier = Supplier(
            organization_id=1,
            code=sup["code"],
            name=sup["name"],
            tin=sup["tin"],
            registration_no=sup["registration_no"],
            msic_code=sup["msic_code"],
            address_line1=sup["address_line1"],
            city=sup["city"],
            state=sup["state"],
            postcode=sup["postcode"],
            country=sup["country"],
            phone=sup["phone"],
            email=sup["email"],
            contact_person=sup["contact_person"],
            currency=sup["currency_code"],
            payment_terms_days=sup["payment_terms_days"],
            credit_limit=Decimal(sup["credit_limit"]),
            is_active=True,
        )
        session.add(supplier)
        created += 1
        log.info("supplier_created", code=sup["code"], name=sup["name"])

    await session.flush()
    log.info("suppliers_seeded", total=len(SUPPLIERS), created=created, skipped=len(SUPPLIERS) - created)
    return created


async def main() -> None:
    import logging

    logging.basicConfig(level=logging.INFO)

    engine = create_async_engine(settings.DATABASE_URL, echo=False)
    SessionLocal = async_sessionmaker(engine, class_=AsyncSession, expire_on_commit=False)

    async with SessionLocal() as session:
        async with session.begin():
            created = await seed_suppliers(session)

    await engine.dispose()
    log.info("seed_complete", message=f"Suppliers seeded: {created} created.")
    print(f"\n✅ Seed complete — {created} suppliers created (existing skipped).")


if __name__ == "__main__":
    asyncio.run(main())
