"""initial_schema

Revision ID: 8058342b33b7
Revises: 
Create Date: 2026-04-23 16:06:57.432885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8058342b33b7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currencies',
    sa.Column('code', sa.String(length=3), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('symbol', sa.String(length=8), nullable=False),
    sa.Column('decimal_places', sa.SmallInteger(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('login_attempts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=False),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('failure_reason', sa.String(length=120), nullable=True),
    sa.Column('attempted_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_login_email_time', 'login_attempts', ['email', 'attempted_at'], unique=False)
    op.create_index('ix_login_ip_time', 'login_attempts', ['ip', 'attempted_at'], unique=False)
    op.create_table('msic_codes',
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('category', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('registration_no', sa.String(length=64), nullable=True),
    sa.Column('tin', sa.String(length=16), nullable=True),
    sa.Column('sst_registration_no', sa.String(length=32), nullable=True),
    sa.Column('msic_code', sa.String(length=8), nullable=True),
    sa.Column('default_currency', sa.String(length=3), nullable=False),
    sa.Column('address_line1', sa.String(length=200), nullable=True),
    sa.Column('address_line2', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=80), nullable=True),
    sa.Column('state', sa.String(length=80), nullable=True),
    sa.Column('postcode', sa.String(length=16), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('ai_master_enabled', sa.Boolean(), nullable=False),
    sa.Column('ai_features', sa.JSON(), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('module', sa.String(length=32), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('brands',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('logo_url', sa.String(length=512), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name='fk_brands_org'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'code', name='uq_brands_org_code')
    )
    op.create_index(op.f('ix_brands_organization_id'), 'brands', ['organization_id'], unique=False)
    op.create_table('categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('name_zh', sa.String(length=120), nullable=True),
    sa.Column('path', sa.String(length=512), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name='fk_categories_org'),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], name='fk_categories_parent'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'code', name='uq_categories_org_code')
    )
    op.create_index(op.f('ix_categories_organization_id'), 'categories', ['organization_id'], unique=False)
    op.create_index('ix_categories_parent', 'categories', ['parent_id'], unique=False)
    op.create_table('document_sequences',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('doc_type', sa.String(length=16), nullable=False),
    sa.Column('year', sa.SmallInteger(), nullable=False),
    sa.Column('current_value', sa.Integer(), nullable=False),
    sa.Column('last_generated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name='fk_docseq_org'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'doc_type', 'year', name='uq_docseq')
    )
    op.create_index(op.f('ix_document_sequences_organization_id'), 'document_sequences', ['organization_id'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('default_home', sa.String(length=64), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name='fk_roles_org'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'code', name='uq_roles_org_code')
    )
    op.create_index(op.f('ix_roles_organization_id'), 'roles', ['organization_id'], unique=False)
    op.create_table('tax_rates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('tax_type', sa.Enum('SALES_TAX', 'SERVICE_TAX', 'EXEMPT', name='taxtype'), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name='fk_tax_rates_org'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'code', name='uq_tax_rates_org_code')
    )
    op.create_index(op.f('ix_tax_rates_organization_id'), 'tax_rates', ['organization_id'], unique=False)
    op.create_table('uoms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('name_zh', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name='fk_uoms_org'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'code', name='uq_uoms_org_code')
    )
    op.create_index(op.f('ix_uoms_organization_id'), 'uoms', ['organization_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('locale', sa.String(length=8), nullable=False),
    sa.Column('theme', sa.String(length=8), nullable=False),
    sa.Column('default_warehouse_id', sa.Integer(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_ip', sa.String(length=45), nullable=True),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['default_warehouse_id'], ['warehouses.id'], name='fk_users_default_wh', use_alter=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name='fk_users_org'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'email', name='uq_users_org_email')
    )
    op.create_index('ix_users_org_active', 'users', ['organization_id', 'is_active', 'deleted_at'], unique=False)
    op.create_index(op.f('ix_users_organization_id'), 'users', ['organization_id'], unique=False)
    op.create_table('ai_call_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('feature', sa.Enum('OCR_INVOICE', 'EINVOICE_PRECHECK', 'DASHBOARD_SUMMARY', 'OTHER', name='aifeature'), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('endpoint', sa.String(length=128), nullable=True),
    sa.Column('prompt_version', sa.String(length=16), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('SUCCESS', 'FAILURE', 'TIMEOUT', 'RATE_LIMITED', 'DISABLED', name='aicallstatus'), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name='fk_ailog_org'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_ailog_user'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ailog_org_feat_date', 'ai_call_logs', ['organization_id', 'feature', 'created_at'], unique=False)
    op.create_index('ix_ailog_user', 'ai_call_logs', ['user_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Enum('CREATED', 'UPDATED', 'DELETED', 'RESTORED', 'STATUS_CHANGED', 'APPROVED', 'CANCELLED', 'SUBMITTED', 'VALIDATED', 'REJECTED', 'FINALIZED', name='auditaction'), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('before', sa.JSON(), nullable=True),
    sa.Column('after', sa.JSON(), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name='fk_audit_actor'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name='fk_audit_org'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_entity', 'audit_logs', ['entity_type', 'entity_id', 'occurred_at'], unique=False)
    op.create_index('ix_audit_org_actor', 'audit_logs', ['organization_id', 'actor_user_id', 'occurred_at'], unique=False)
    op.create_table('customers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('name_zh', sa.String(length=200), nullable=True),
    sa.Column('customer_type', sa.Enum('B2B', 'B2C', name='customertype'), nullable=False),
    sa.Column('registration_no', sa.String(length=64), nullable=True),
    sa.Column('tin', sa.String(length=16), nullable=True),
    sa.Column('sst_registration_no', sa.String(length=32), nullable=True),
    sa.Column('msic_code', sa.String(length=8), nullable=True),
    sa.Column('contact_person', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('address_line1', sa.String(length=200), nullable=True),
    sa.Column('address_line2', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=80), nullable=True),
    sa.Column('state', sa.String(length=80), nullable=True),
    sa.Column('postcode', sa.String(length=16), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('payment_terms_days', sa.Integer(), nullable=False),
    sa.Column('credit_limit', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='fk_customers_created_by'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name='fk_customers_org'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name='fk_customers_updated_by'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'code', name='uq_customers_org_code')
    )
    op.create_index('ix_customers_org_active', 'customers', ['organization_id', 'is_active', 'deleted_at'], unique=False)
    op.create_index('ix_customers_org_type', 'customers', ['organization_id', 'customer_type'], unique=False)
    op.create_index(op.f('ix_customers_organization_id'), 'customers', ['organization_id'], unique=False)
    op.create_table('demo_reset_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('triggered_by', sa.Enum('SCHEDULED', 'MANUAL', name='demoresettrigger'), nullable=False),
    sa.Column('triggered_by_user_id', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('RUNNING', 'SUCCESS', 'FAILURE', 'ROLLED_BACK', name='demoresetstatus'), nullable=False),
    sa.Column('backup_path', sa.String(length=512), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('tables_reset', sa.JSON(), nullable=True),
    sa.Column('records_deleted', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['triggered_by_user_id'], ['users.id'], name='fk_demoreset_user'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_demoreset_status_time', 'demo_reset_logs', ['status', 'started_at'], unique=False)
    op.create_table('exchange_rates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('from_currency', sa.String(length=3), nullable=False),
    sa.Column('to_currency', sa.String(length=3), nullable=False),
    sa.Column('rate', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='fk_exchange_rates_creator'),
    sa.ForeignKeyConstraint(['from_currency'], ['currencies.code'], name='fk_exchange_rates_from'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name='fk_exchange_rates_org'),
    sa.ForeignKeyConstraint(['to_currency'], ['currencies.code'], name='fk_exchange_rates_to'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_exchange_rates_lookup', 'exchange_rates', ['organization_id', 'from_currency', 'to_currency', 'effective_from'], unique=False)
    op.create_index(op.f('ix_exchange_rates_organization_id'), 'exchange_rates', ['organization_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('LOW_STOCK', 'APPROVAL_PENDING', 'EINVOICE_VALIDATED', 'EINVOICE_REJECTED', 'EINVOICE_EXPIRING', 'PAYMENT_RECEIVED', 'ORDER_CANCELLED', 'DEMO_RESET_DONE', 'OTHER', name='notificationtype'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('i18n_key', sa.String(length=128), nullable=True),
    sa.Column('i18n_params', sa.JSON(), nullable=True),
    sa.Column('target_user_id', sa.Integer(), nullable=True),
    sa.Column('target_role', sa.String(length=32), nullable=True),
    sa.Column('related_entity_type', sa.String(length=32), nullable=True),
    sa.Column('related_entity_id', sa.Integer(), nullable=True),
    sa.Column('action_url', sa.String(length=512), nullable=True),
    sa.Column('severity', sa.Enum('INFO', 'WARNING', 'ERROR', 'CRITICAL', name='notificationseverity'), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name='fk_notif_org'),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], name='fk_notif_user'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notif_org_type', 'notifications', ['organization_id', 'type', 'created_at'], unique=False)
    op.create_index('ix_notif_role_read', 'notifications', ['target_role', 'is_read', 'created_at'], unique=False)
    op.create_index('ix_notif_user_read', 'notifications', ['target_user_id', 'is_read', 'created_at'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name='fk_rp_perm', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name='fk_rp_role', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_index('ix_role_permissions_perm', 'role_permissions', ['permission_id'], unique=False)
    op.create_table('skus',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('barcode', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('name_zh', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('brand_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('base_uom_id', sa.Integer(), nullable=False),
    sa.Column('tax_rate_id', sa.Integer(), nullable=False),
    sa.Column('msic_code', sa.String(length=8), nullable=True),
    sa.Column('unit_price_excl_tax', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('unit_price_incl_tax', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('price_tax_inclusive', sa.Boolean(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('costing_method', sa.Enum('WEIGHTED_AVERAGE', 'FIFO', 'SPECIFIC', name='costingmethod'), nullable=False),
    sa.Column('last_cost', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('safety_stock', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('reorder_point', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('reorder_qty', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('track_batch', sa.Boolean(), nullable=False),
    sa.Column('track_expiry', sa.Boolean(), nullable=False),
    sa.Column('track_serial', sa.Boolean(), nullable=False),
    sa.Column('shelf_life_days', sa.Integer(), nullable=True),
    sa.Column('image_url', sa.String(length=512), nullable=True),
    sa.Column('weight_kg', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('aliases', sa.JSON(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['base_uom_id'], ['uoms.id'], name='fk_skus_uom'),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], name='fk_skus_brand'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name='fk_skus_category'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='fk_skus_created_by'),
    sa.ForeignKeyConstraint(['msic_code'], ['msic_codes.code'], name='fk_skus_msic'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name='fk_skus_org'),
    sa.ForeignKeyConstraint(['tax_rate_id'], ['tax_rates.id'], name='fk_skus_tax'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name='fk_skus_updated_by'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'code', name='uq_skus_org_code')
    )
    op.create_index('ix_skus_barcode', 'skus', ['barcode'], unique=False)
    op.create_index('ix_skus_org_active', 'skus', ['organization_id', 'is_active', 'deleted_at'], unique=False)
    op.create_index('ix_skus_org_brand', 'skus', ['organization_id', 'brand_id'], unique=False)
    op.create_index('ix_skus_org_category', 'skus', ['organization_id', 'category_id'], unique=False)
    op.create_index(op.f('ix_skus_organization_id'), 'skus', ['organization_id'], unique=False)
    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('name_zh', sa.String(length=200), nullable=True),
    sa.Column('registration_no', sa.String(length=64), nullable=True),
    sa.Column('tin', sa.String(length=16), nullable=True),
    sa.Column('sst_registration_no', sa.String(length=32), nullable=True),
    sa.Column('msic_code', sa.String(length=8), nullable=True),
    sa.Column('contact_person', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('address_line1', sa.String(length=200), nullable=True),
    sa.Column('address_line2', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=80), nullable=True),
    sa.Column('state', sa.String(length=80), nullable=True),
    sa.Column('postcode', sa.String(length=16), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('payment_terms_days', sa.Integer(), nullable=False),
    sa.Column('credit_limit', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='fk_suppliers_created_by'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name='fk_suppliers_org'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name='fk_suppliers_updated_by'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'code', name='uq_suppliers_org_code')
    )
    op.create_index('ix_suppliers_org_active', 'suppliers', ['organization_id', 'is_active', 'deleted_at'], unique=False)
    op.create_index(op.f('ix_suppliers_organization_id'), 'suppliers', ['organization_id'], unique=False)
    op.create_table('uploaded_files',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('OCR_INVOICE', 'EINVOICE_PDF', 'AVATAR', 'LOGO', 'IMPORT_EXCEL', 'REJECTION_ATTACHMENT', 'OTHER', name='filecategory'), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_path', sa.String(length=512), nullable=False),
    sa.Column('mime_type', sa.String(length=128), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('related_entity_type', sa.String(length=32), nullable=True),
    sa.Column('related_entity_id', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name='fk_files_org'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name='fk_files_user'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_files_expires', 'uploaded_files', ['expires_at'], unique=False)
    op.create_index('ix_files_org_category', 'uploaded_files', ['organization_id', 'category', 'created_at'], unique=False)
    op.create_index('ix_files_related', 'uploaded_files', ['related_entity_type', 'related_entity_id'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name='fk_ur_role', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_ur_user', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_index('ix_user_roles_role', 'user_roles', ['role_id'], unique=False)
    op.create_table('warehouses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('type', sa.Enum('MAIN', 'BRANCH', 'TRANSIT', 'QUARANTINE', name='warehousetype'), nullable=False),
    sa.Column('address_line1', sa.String(length=200), nullable=True),
    sa.Column('address_line2', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=80), nullable=True),
    sa.Column('state', sa.String(length=80), nullable=True),
    sa.Column('postcode', sa.String(length=16), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('manager_user_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['manager_user_id'], ['users.id'], name='fk_warehouses_manager'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name='fk_warehouses_org'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'code', name='uq_warehouses_org_code')
    )
    op.create_index('ix_warehouses_org_active', 'warehouses', ['organization_id', 'is_active', 'deleted_at'], unique=False)
    op.create_index(op.f('ix_warehouses_organization_id'), 'warehouses', ['organization_id'], unique=False)
    # Deferred FK: users.default_warehouse_id -> warehouses (circular dependency resolved after both tables exist)
    op.create_foreign_key('fk_users_default_wh', 'users', 'warehouses', ['default_warehouse_id'], ['id'])
    op.create_table('payments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('document_no', sa.String(length=32), nullable=False),
    sa.Column('direction', sa.Enum('INBOUND', 'OUTBOUND', name='paymentdirection'), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('method', sa.Enum('CASH', 'BANK_TRANSFER', 'FPX', 'DUITNOW', 'CREDIT_CARD', 'CHEQUE', 'OTHER', name='paymentmethod'), nullable=False),
    sa.Column('reference_no', sa.String(length=64), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('exchange_rate', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('base_currency_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('allocated_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('unallocated_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='fk_pay_created_by'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name='fk_pay_customer'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name='fk_pay_org'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name='fk_pay_supplier'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'document_no', name='uq_pay_org_document_no')
    )
    op.create_index('ix_pay_customer', 'payments', ['customer_id'], unique=False)
    op.create_index('ix_pay_org_date', 'payments', ['organization_id', 'business_date'], unique=False)
    op.create_index('ix_pay_supplier', 'payments', ['supplier_id'], unique=False)
    op.create_index(op.f('ix_payments_organization_id'), 'payments', ['organization_id'], unique=False)
    op.create_table('purchase_orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('document_no', sa.String(length=32), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'CONFIRMED', 'PARTIAL_RECEIVED', 'FULLY_RECEIVED', 'CANCELLED', name='postatus'), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('expected_date', sa.Date(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('exchange_rate', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('subtotal_excl_tax', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('shipping_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('total_incl_tax', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('base_currency_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('payment_terms_days', sa.Integer(), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('cancel_reason', sa.String(length=500), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('source', sa.Enum('MANUAL', 'OCR', 'IMPORT', 'API', name='posource'), nullable=False),
    sa.Column('source_file_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='fk_po_created_by'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name='fk_po_org'),
    sa.ForeignKeyConstraint(['source_file_id'], ['uploaded_files.id'], name='fk_po_source_file'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name='fk_po_supplier'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name='fk_po_updated_by'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], name='fk_po_warehouse'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'document_no', name='uq_po_org_document_no')
    )
    op.create_index('ix_po_org_status_date', 'purchase_orders', ['organization_id', 'status', 'business_date'], unique=False)
    op.create_index('ix_po_supplier', 'purchase_orders', ['supplier_id'], unique=False)
    op.create_index('ix_po_warehouse', 'purchase_orders', ['warehouse_id'], unique=False)
    op.create_index(op.f('ix_purchase_orders_organization_id'), 'purchase_orders', ['organization_id'], unique=False)
    op.create_table('sales_orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('document_no', sa.String(length=32), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'CONFIRMED', 'PARTIAL_SHIPPED', 'FULLY_SHIPPED', 'INVOICED', 'PAID', 'CANCELLED', name='sostatus'), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('expected_ship_date', sa.Date(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('exchange_rate', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('subtotal_excl_tax', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('shipping_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('total_incl_tax', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('base_currency_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('payment_terms_days', sa.Integer(), nullable=False),
    sa.Column('shipping_address', sa.String(length=500), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('cancel_reason', sa.String(length=500), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('fully_shipped_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='fk_so_created_by'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name='fk_so_customer'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name='fk_so_org'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name='fk_so_updated_by'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], name='fk_so_warehouse'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'document_no', name='uq_so_org_document_no')
    )
    op.create_index(op.f('ix_sales_orders_organization_id'), 'sales_orders', ['organization_id'], unique=False)
    op.create_index('ix_so_customer', 'sales_orders', ['customer_id'], unique=False)
    op.create_index('ix_so_org_status_date', 'sales_orders', ['organization_id', 'status', 'business_date'], unique=False)
    op.create_index('ix_so_warehouse', 'sales_orders', ['warehouse_id'], unique=False)
    op.create_table('stock_adjustments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('document_no', sa.String(length=32), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'CONFIRMED', 'CANCELLED', name='stockadjustmentstatus'), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.Enum('PHYSICAL_COUNT', 'DAMAGE', 'THEFT', 'CORRECTION', 'EXPIRY', 'OTHER', name='stockadjustmentreason'), nullable=False),
    sa.Column('reason_description', sa.String(length=500), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('remarks', sa.String(length=500), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], name='fk_adj_approved_by'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='fk_adj_created_by'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name='fk_adj_org'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], name='fk_adj_warehouse'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'document_no', name='uq_adj_org_document_no')
    )
    op.create_index('ix_adj_org_status_date', 'stock_adjustments', ['organization_id', 'status', 'business_date'], unique=False)
    op.create_index('ix_adj_warehouse', 'stock_adjustments', ['warehouse_id'], unique=False)
    op.create_index(op.f('ix_stock_adjustments_organization_id'), 'stock_adjustments', ['organization_id'], unique=False)
    op.create_table('stock_movements',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('sku_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('movement_type', sa.Enum('PURCHASE_IN', 'PURCHASE_RETURN', 'SALES_OUT', 'SALES_RETURN', 'TRANSFER_OUT', 'TRANSFER_IN', 'ADJUSTMENT_IN', 'ADJUSTMENT_OUT', 'RESERVE', 'UNRESERVE', 'QUALITY_HOLD', 'QUALITY_RELEASE', name='stockmovementtype'), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('avg_cost_after', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('source_document_type', sa.Enum('PO', 'SO', 'GR', 'DO', 'CN', 'TRANSFER', 'ADJUSTMENT', 'OPENING', 'DEMO_RESET', name='stockmovementsourcetype'), nullable=False),
    sa.Column('source_document_id', sa.Integer(), nullable=False),
    sa.Column('source_line_id', sa.Integer(), nullable=True),
    sa.Column('batch_no', sa.String(length=64), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('serial_no', sa.String(length=128), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name='fk_sm_actor'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name='fk_sm_org'),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], name='fk_sm_sku'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], name='fk_sm_warehouse'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sm_org_type_date', 'stock_movements', ['organization_id', 'movement_type', 'occurred_at'], unique=False)
    op.create_index('ix_sm_sku_warehouse', 'stock_movements', ['sku_id', 'warehouse_id', 'occurred_at'], unique=False)
    op.create_index('ix_sm_source', 'stock_movements', ['source_document_type', 'source_document_id'], unique=False)
    op.create_table('stock_transfers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('document_no', sa.String(length=32), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'CONFIRMED', 'IN_TRANSIT', 'RECEIVED', 'CANCELLED', name='stocktransferstatus'), nullable=False),
    sa.Column('from_warehouse_id', sa.Integer(), nullable=False),
    sa.Column('to_warehouse_id', sa.Integer(), nullable=False),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('expected_arrival_date', sa.Date(), nullable=True),
    sa.Column('actual_arrival_date', sa.Date(), nullable=True),
    sa.Column('remarks', sa.String(length=500), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='fk_tr_created_by'),
    sa.ForeignKeyConstraint(['from_warehouse_id'], ['warehouses.id'], name='fk_tr_from_wh'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name='fk_tr_org'),
    sa.ForeignKeyConstraint(['to_warehouse_id'], ['warehouses.id'], name='fk_tr_to_wh'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name='fk_tr_updated_by'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'document_no', name='uq_tr_org_document_no')
    )
    op.create_index(op.f('ix_stock_transfers_organization_id'), 'stock_transfers', ['organization_id'], unique=False)
    op.create_index('ix_tr_from_wh', 'stock_transfers', ['from_warehouse_id'], unique=False)
    op.create_index('ix_tr_org_status_date', 'stock_transfers', ['organization_id', 'status', 'business_date'], unique=False)
    op.create_index('ix_tr_to_wh', 'stock_transfers', ['to_warehouse_id'], unique=False)
    op.create_table('stocks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('sku_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('on_hand', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('reserved', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('quality_hold', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('available', sa.Numeric(precision=18, scale=4), sa.Computed('`on_hand` - `reserved` - `quality_hold`', persisted=False), nullable=True),
    sa.Column('incoming', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('in_transit', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('avg_cost', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('last_cost', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('initial_on_hand', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('initial_avg_cost', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('last_movement_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name='fk_stocks_org'),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], name='fk_stocks_sku'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], name='fk_stocks_warehouse'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku_id', 'warehouse_id', name='uq_stocks_sku_warehouse')
    )
    op.create_index('ix_stocks_org', 'stocks', ['organization_id'], unique=False)
    op.create_index('ix_stocks_warehouse', 'stocks', ['warehouse_id'], unique=False)
    op.create_table('delivery_orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('document_no', sa.String(length=32), nullable=False),
    sa.Column('sales_order_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('delivery_date', sa.Date(), nullable=False),
    sa.Column('shipping_method', sa.String(length=64), nullable=True),
    sa.Column('tracking_no', sa.String(length=64), nullable=True),
    sa.Column('delivered_by', sa.Integer(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='fk_do_created_by'),
    sa.ForeignKeyConstraint(['delivered_by'], ['users.id'], name='fk_do_delivered_by'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name='fk_do_org'),
    sa.ForeignKeyConstraint(['sales_order_id'], ['sales_orders.id'], name='fk_do_so'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], name='fk_do_warehouse'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'document_no', name='uq_do_org_document_no')
    )
    op.create_index(op.f('ix_delivery_orders_organization_id'), 'delivery_orders', ['organization_id'], unique=False)
    op.create_index('ix_do_org_date', 'delivery_orders', ['organization_id', 'delivery_date'], unique=False)
    op.create_index('ix_do_so', 'delivery_orders', ['sales_order_id'], unique=False)
    op.create_table('goods_receipts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('document_no', sa.String(length=32), nullable=False),
    sa.Column('purchase_order_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('receipt_date', sa.Date(), nullable=False),
    sa.Column('delivery_note_no', sa.String(length=64), nullable=True),
    sa.Column('received_by', sa.Integer(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='fk_gr_created_by'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name='fk_gr_org'),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], name='fk_gr_po'),
    sa.ForeignKeyConstraint(['received_by'], ['users.id'], name='fk_gr_received_by'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], name='fk_gr_warehouse'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'document_no', name='uq_gr_org_document_no')
    )
    op.create_index(op.f('ix_goods_receipts_organization_id'), 'goods_receipts', ['organization_id'], unique=False)
    op.create_index('ix_gr_org_date', 'goods_receipts', ['organization_id', 'receipt_date'], unique=False)
    op.create_index('ix_gr_po', 'goods_receipts', ['purchase_order_id'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('document_no', sa.String(length=32), nullable=False),
    sa.Column('invoice_type', sa.Enum('INVOICE', 'SELF_BILLED', 'CONSOLIDATED', name='invoicetype'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'VALIDATED', 'FINAL', 'REJECTED', 'CANCELLED', name='invoicestatus'), nullable=False),
    sa.Column('sales_order_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=True),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('exchange_rate', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('subtotal_excl_tax', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('total_incl_tax', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('base_currency_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('paid_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('uin', sa.String(length=64), nullable=True),
    sa.Column('qr_code_url', sa.String(length=512), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('validated_at', sa.DateTime(), nullable=True),
    sa.Column('finalized_at', sa.DateTime(), nullable=True),
    sa.Column('rejected_at', sa.DateTime(), nullable=True),
    sa.Column('rejected_by', sa.Enum('LHDN', 'BUYER', name='rejectedby'), nullable=True),
    sa.Column('rejection_reason', sa.String(length=1000), nullable=True),
    sa.Column('rejection_attachment_id', sa.Integer(), nullable=True),
    sa.Column('precheck_result', sa.JSON(), nullable=True),
    sa.Column('precheck_at', sa.DateTime(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('pdf_file_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='fk_inv_created_by'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name='fk_inv_customer'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name='fk_inv_org'),
    sa.ForeignKeyConstraint(['pdf_file_id'], ['uploaded_files.id'], name='fk_inv_pdf_file'),
    sa.ForeignKeyConstraint(['rejection_attachment_id'], ['uploaded_files.id'], name='fk_inv_rejection_attachment'),
    sa.ForeignKeyConstraint(['sales_order_id'], ['sales_orders.id'], name='fk_inv_so'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name='fk_inv_updated_by'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], name='fk_inv_warehouse'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'document_no', name='uq_inv_org_document_no'),
    sa.UniqueConstraint('uin', name='uq_inv_uin')
    )
    op.create_index('ix_inv_customer', 'invoices', ['customer_id'], unique=False)
    op.create_index('ix_inv_org_status_date', 'invoices', ['organization_id', 'status', 'business_date'], unique=False)
    op.create_index('ix_inv_so', 'invoices', ['sales_order_id'], unique=False)
    op.create_index('ix_inv_validated_at', 'invoices', ['status', 'validated_at'], unique=False)
    op.create_index(op.f('ix_invoices_organization_id'), 'invoices', ['organization_id'], unique=False)
    op.create_table('purchase_order_lines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('purchase_order_id', sa.Integer(), nullable=False),
    sa.Column('line_no', sa.Integer(), nullable=False),
    sa.Column('sku_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('uom_id', sa.Integer(), nullable=False),
    sa.Column('qty_ordered', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('qty_received', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('unit_price_excl_tax', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('tax_rate_id', sa.Integer(), nullable=False),
    sa.Column('tax_rate_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('discount_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('line_total_excl_tax', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('line_total_incl_tax', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('batch_no', sa.String(length=64), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], name='fk_pol_po', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], name='fk_pol_sku'),
    sa.ForeignKeyConstraint(['tax_rate_id'], ['tax_rates.id'], name='fk_pol_tax'),
    sa.ForeignKeyConstraint(['uom_id'], ['uoms.id'], name='fk_pol_uom'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('purchase_order_id', 'line_no', name='uq_pol_po_lineno')
    )
    op.create_index('ix_pol_sku', 'purchase_order_lines', ['sku_id'], unique=False)
    op.create_table('sales_order_lines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sales_order_id', sa.Integer(), nullable=False),
    sa.Column('line_no', sa.Integer(), nullable=False),
    sa.Column('sku_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('uom_id', sa.Integer(), nullable=False),
    sa.Column('qty_ordered', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('qty_shipped', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('qty_invoiced', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('unit_price_excl_tax', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('tax_rate_id', sa.Integer(), nullable=False),
    sa.Column('tax_rate_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('discount_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('line_total_excl_tax', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('line_total_incl_tax', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('snapshot_avg_cost', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('batch_no', sa.String(length=64), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('serial_no', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['sales_order_id'], ['sales_orders.id'], name='fk_sol_so', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], name='fk_sol_sku'),
    sa.ForeignKeyConstraint(['tax_rate_id'], ['tax_rates.id'], name='fk_sol_tax'),
    sa.ForeignKeyConstraint(['uom_id'], ['uoms.id'], name='fk_sol_uom'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sales_order_id', 'line_no', name='uq_sol_so_lineno')
    )
    op.create_index('ix_sol_sku', 'sales_order_lines', ['sku_id'], unique=False)
    op.create_table('stock_adjustment_lines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stock_adjustment_id', sa.Integer(), nullable=False),
    sa.Column('line_no', sa.Integer(), nullable=False),
    sa.Column('sku_id', sa.Integer(), nullable=False),
    sa.Column('uom_id', sa.Integer(), nullable=False),
    sa.Column('qty_before', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('qty_after', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('qty_diff', sa.Numeric(precision=18, scale=4), sa.Computed('`qty_after` - `qty_before`', persisted=False), nullable=True),
    sa.Column('unit_cost', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('batch_no', sa.String(length=64), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], name='fk_adjl_sku'),
    sa.ForeignKeyConstraint(['stock_adjustment_id'], ['stock_adjustments.id'], name='fk_adjl_adj', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uom_id'], ['uoms.id'], name='fk_adjl_uom'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_adjustment_id', 'line_no', name='uq_adjl_adj_lineno')
    )
    op.create_index('ix_adjl_sku', 'stock_adjustment_lines', ['sku_id'], unique=False)
    op.create_table('stock_transfer_lines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stock_transfer_id', sa.Integer(), nullable=False),
    sa.Column('line_no', sa.Integer(), nullable=False),
    sa.Column('sku_id', sa.Integer(), nullable=False),
    sa.Column('uom_id', sa.Integer(), nullable=False),
    sa.Column('qty_sent', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('qty_received', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('unit_cost_snapshot', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('batch_no', sa.String(length=64), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], name='fk_trl_sku'),
    sa.ForeignKeyConstraint(['stock_transfer_id'], ['stock_transfers.id'], name='fk_trl_tr', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uom_id'], ['uoms.id'], name='fk_trl_uom'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_transfer_id', 'line_no', name='uq_trl_tr_lineno')
    )
    op.create_index('ix_trl_sku', 'stock_transfer_lines', ['sku_id'], unique=False)
    op.create_table('credit_notes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('document_no', sa.String(length=32), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'VALIDATED', 'FINAL', 'REJECTED', 'CANCELLED', name='creditnotestatus'), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.Enum('RETURN', 'DISCOUNT_ADJUSTMENT', 'PRICE_CORRECTION', 'WRITE_OFF', 'OTHER', name='creditnotereason'), nullable=False),
    sa.Column('reason_description', sa.String(length=500), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('exchange_rate', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('subtotal_excl_tax', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('total_incl_tax', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('base_currency_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('uin', sa.String(length=64), nullable=True),
    sa.Column('qr_code_url', sa.String(length=512), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('validated_at', sa.DateTime(), nullable=True),
    sa.Column('finalized_at', sa.DateTime(), nullable=True),
    sa.Column('rejected_at', sa.DateTime(), nullable=True),
    sa.Column('rejection_reason', sa.String(length=1000), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('pdf_file_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='fk_cn_created_by'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name='fk_cn_customer'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name='fk_cn_invoice'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name='fk_cn_org'),
    sa.ForeignKeyConstraint(['pdf_file_id'], ['uploaded_files.id'], name='fk_cn_pdf_file'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name='fk_cn_updated_by'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'document_no', name='uq_cn_org_document_no')
    )
    op.create_index('ix_cn_customer', 'credit_notes', ['customer_id'], unique=False)
    op.create_index('ix_cn_invoice', 'credit_notes', ['invoice_id'], unique=False)
    op.create_index('ix_cn_org_status_date', 'credit_notes', ['organization_id', 'status', 'business_date'], unique=False)
    op.create_index(op.f('ix_credit_notes_organization_id'), 'credit_notes', ['organization_id'], unique=False)
    op.create_table('delivery_order_lines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('delivery_order_id', sa.Integer(), nullable=False),
    sa.Column('sales_order_line_id', sa.Integer(), nullable=False),
    sa.Column('line_no', sa.Integer(), nullable=False),
    sa.Column('sku_id', sa.Integer(), nullable=False),
    sa.Column('uom_id', sa.Integer(), nullable=False),
    sa.Column('qty_shipped', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('batch_no', sa.String(length=64), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('serial_no', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['delivery_order_id'], ['delivery_orders.id'], name='fk_dol_do', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sales_order_line_id'], ['sales_order_lines.id'], name='fk_dol_sol'),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], name='fk_dol_sku'),
    sa.ForeignKeyConstraint(['uom_id'], ['uoms.id'], name='fk_dol_uom'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_dol_do', 'delivery_order_lines', ['delivery_order_id'], unique=False)
    op.create_index('ix_dol_sol', 'delivery_order_lines', ['sales_order_line_id'], unique=False)
    op.create_table('goods_receipt_lines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('goods_receipt_id', sa.Integer(), nullable=False),
    sa.Column('purchase_order_line_id', sa.Integer(), nullable=False),
    sa.Column('line_no', sa.Integer(), nullable=False),
    sa.Column('sku_id', sa.Integer(), nullable=False),
    sa.Column('uom_id', sa.Integer(), nullable=False),
    sa.Column('qty_received', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('batch_no', sa.String(length=64), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('remarks', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['goods_receipt_id'], ['goods_receipts.id'], name='fk_grl_gr', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['purchase_order_line_id'], ['purchase_order_lines.id'], name='fk_grl_pol'),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], name='fk_grl_sku'),
    sa.ForeignKeyConstraint(['uom_id'], ['uoms.id'], name='fk_grl_uom'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_grl_gr', 'goods_receipt_lines', ['goods_receipt_id'], unique=False)
    op.create_index('ix_grl_pol', 'goods_receipt_lines', ['purchase_order_line_id'], unique=False)
    op.create_index('ix_grl_sku', 'goods_receipt_lines', ['sku_id'], unique=False)
    op.create_table('invoice_lines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('sales_order_line_id', sa.Integer(), nullable=True),
    sa.Column('line_no', sa.Integer(), nullable=False),
    sa.Column('sku_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('uom_id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('unit_price_excl_tax', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('tax_rate_id', sa.Integer(), nullable=False),
    sa.Column('tax_rate_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('line_total_excl_tax', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('line_total_incl_tax', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('msic_code', sa.String(length=8), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name='fk_invl_inv', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sales_order_line_id'], ['sales_order_lines.id'], name='fk_invl_sol'),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], name='fk_invl_sku'),
    sa.ForeignKeyConstraint(['tax_rate_id'], ['tax_rates.id'], name='fk_invl_tax'),
    sa.ForeignKeyConstraint(['uom_id'], ['uoms.id'], name='fk_invl_uom'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_id', 'line_no', name='uq_invl_inv_lineno')
    )
    op.create_index('ix_invl_sku', 'invoice_lines', ['sku_id'], unique=False)
    op.create_index('ix_invl_sol', 'invoice_lines', ['sales_order_line_id'], unique=False)
    op.create_table('credit_note_lines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('credit_note_id', sa.Integer(), nullable=False),
    sa.Column('invoice_line_id', sa.Integer(), nullable=False),
    sa.Column('line_no', sa.Integer(), nullable=False),
    sa.Column('sku_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('uom_id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('unit_price_excl_tax', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('tax_rate_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('line_total_excl_tax', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('line_total_incl_tax', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('snapshot_avg_cost', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['credit_note_id'], ['credit_notes.id'], name='fk_cnl_cn', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invoice_line_id'], ['invoice_lines.id'], name='fk_cnl_invl'),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], name='fk_cnl_sku'),
    sa.ForeignKeyConstraint(['uom_id'], ['uoms.id'], name='fk_cnl_uom'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('credit_note_id', 'line_no', name='uq_cnl_cn_lineno')
    )
    op.create_index('ix_cnl_invl', 'credit_note_lines', ['invoice_line_id'], unique=False)
    op.create_table('payment_allocations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.Column('purchase_order_id', sa.Integer(), nullable=True),
    sa.Column('credit_note_id', sa.Integer(), nullable=True),
    sa.Column('allocated_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('allocated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='fk_palloc_created_by'),
    sa.ForeignKeyConstraint(['credit_note_id'], ['credit_notes.id'], name='fk_palloc_cn'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name='fk_palloc_invoice'),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], name='fk_palloc_payment', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], name='fk_palloc_po'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_palloc_cn', 'payment_allocations', ['credit_note_id'], unique=False)
    op.create_index('ix_palloc_invoice', 'payment_allocations', ['invoice_id'], unique=False)
    op.create_index('ix_palloc_payment', 'payment_allocations', ['payment_id'], unique=False)
    op.create_index('ix_palloc_po', 'payment_allocations', ['purchase_order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # Drop tables in reverse dependency order; DROP TABLE auto-removes indexes and inline FKs
    op.drop_table("payment_allocations")
    op.drop_table("credit_note_lines")
    op.drop_table("invoice_lines")
    op.drop_table("goods_receipt_lines")
    op.drop_table("delivery_order_lines")
    op.drop_table("stock_transfer_lines")
    op.drop_table("stock_adjustment_lines")
    op.drop_table("stock_movements")
    op.drop_table("credit_notes")
    op.drop_table("invoices")
    op.drop_table("sales_order_lines")
    op.drop_table("purchase_order_lines")
    op.drop_table("goods_receipts")
    op.drop_table("delivery_orders")
    op.drop_table("stocks")
    op.drop_table("sales_orders")
    op.drop_table("purchase_orders")
    op.drop_table("payments")
    op.drop_table("skus")
    op.drop_table("suppliers")
    op.drop_table("customers")
    op.drop_table("notifications")
    op.drop_table("document_sequences")
    op.drop_table("exchange_rates")
    op.drop_table("audit_logs")
    op.drop_table("ai_call_logs")
    op.drop_table("uploaded_files")
    op.drop_table("demo_reset_logs")
    op.drop_table("stock_adjustments")
    op.drop_table("stock_transfers")
    op.drop_table("user_roles")
    op.drop_table("role_permissions")
    # Drop deferred FK (users.default_warehouse_id -> warehouses) before dropping warehouses
    op.drop_constraint("fk_users_default_wh", "users", type_="foreignkey")
    op.drop_table("warehouses")
    op.drop_table("users")
    op.drop_table("roles")
    op.drop_table("brands")
    op.drop_table("categories")
    op.drop_table("tax_rates")
    op.drop_table("uoms")
    op.drop_table("login_attempts")
    op.drop_table("permissions")
    op.drop_table("organizations")
    op.drop_table("currencies")
    op.drop_table("msic_codes")
    # ### end Alembic commands ###
